// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.5.1
// source: proto/wxproto/reply_msg.proto

package wxproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 发送回复(引用)消息的protobuf结构
// CG路径: /cgi-bin/micromsg-bin/sendappmsg
// 消息类型: appmsg type=57
type WxSendReplyMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *ReplyMsgHeader        `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Body          *ReplyMsgBody          `protobuf:"bytes,2,opt,name=body" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WxSendReplyMsg) Reset() {
	*x = WxSendReplyMsg{}
	mi := &file_proto_wxproto_reply_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WxSendReplyMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WxSendReplyMsg) ProtoMessage() {}

func (x *WxSendReplyMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wxproto_reply_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WxSendReplyMsg.ProtoReflect.Descriptor instead.
func (*WxSendReplyMsg) Descriptor() ([]byte, []int) {
	return file_proto_wxproto_reply_msg_proto_rawDescGZIP(), []int{0}
}

func (x *WxSendReplyMsg) GetHeader() *ReplyMsgHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *WxSendReplyMsg) GetBody() *ReplyMsgBody {
	if x != nil {
		return x.Body
	}
	return nil
}

// Header: 固定64字节
type ReplyMsgHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flag          []byte                 `protobuf:"bytes,1,opt,name=flag" json:"flag,omitempty"`                                  // 固定 [0x00]
	Timestamp     *uint32                `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`                       // 请求时间戳(秒)
	ClientProof   []byte                 `protobuf:"bytes,3,opt,name=client_proof,json=clientProof" json:"client_proof,omitempty"` // 16字节随机数据/md5
	DeviceId      *uint64                `protobuf:"varint,4,opt,name=device_id,json=deviceId" json:"device_id,omitempty"`         // 设备标识(大整数)
	Platform      *string                `protobuf:"bytes,5,opt,name=platform" json:"platform,omitempty"`                          // 平台信息 "UnifiedPCMac 26 arm64"
	Version       *uint32                `protobuf:"varint,6,opt,name=version" json:"version,omitempty"`                           // 版本/标记 = 163
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyMsgHeader) Reset() {
	*x = ReplyMsgHeader{}
	mi := &file_proto_wxproto_reply_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyMsgHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyMsgHeader) ProtoMessage() {}

func (x *ReplyMsgHeader) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wxproto_reply_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyMsgHeader.ProtoReflect.Descriptor instead.
func (*ReplyMsgHeader) Descriptor() ([]byte, []int) {
	return file_proto_wxproto_reply_msg_proto_rawDescGZIP(), []int{1}
}

func (x *ReplyMsgHeader) GetFlag() []byte {
	if x != nil {
		return x.Flag
	}
	return nil
}

func (x *ReplyMsgHeader) GetTimestamp() uint32 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *ReplyMsgHeader) GetClientProof() []byte {
	if x != nil {
		return x.ClientProof
	}
	return nil
}

func (x *ReplyMsgHeader) GetDeviceId() uint64 {
	if x != nil && x.DeviceId != nil {
		return *x.DeviceId
	}
	return 0
}

func (x *ReplyMsgHeader) GetPlatform() string {
	if x != nil && x.Platform != nil {
		return *x.Platform
	}
	return ""
}

func (x *ReplyMsgHeader) GetVersion() uint32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

// Body: 消息体
type ReplyMsgBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        *string                `protobuf:"bytes,1,opt,name=sender" json:"sender,omitempty"`                                     // 接收方wxid (field1是target)
	Unknown2      []byte                 `protobuf:"bytes,2,opt,name=unknown2" json:"unknown2,omitempty"`                                 // 空 (必须显式存在)
	Unknown3      *int32                 `protobuf:"varint,3,opt,name=unknown3" json:"unknown3,omitempty"`                                // 0 (必须显式存在)
	Receiver      *string                `protobuf:"bytes,4,opt,name=receiver" json:"receiver,omitempty"`                                 // 发送方wxid
	MsgType       *int32                 `protobuf:"varint,5,opt,name=msg_type,json=msgType" json:"msg_type,omitempty"`                   // 消息类型 = 57
	Content       []byte                 `protobuf:"bytes,6,opt,name=content" json:"content,omitempty"`                                   // XML内容 (appmsg XML)
	SendTimestamp *int64                 `protobuf:"varint,7,opt,name=send_timestamp,json=sendTimestamp" json:"send_timestamp,omitempty"` // 发送时间戳
	ClientMsgId   *string                `protobuf:"bytes,8,opt,name=client_msg_id,json=clientMsgId" json:"client_msg_id,omitempty"`      // 消息ID
	Unknown9      *int32                 `protobuf:"varint,9,opt,name=unknown9" json:"unknown9,omitempty"`                                // 0
	Flag          *int32                 `protobuf:"varint,10,opt,name=flag" json:"flag,omitempty"`                                       // 1
	Unknown11     *int32                 `protobuf:"varint,11,opt,name=unknown11" json:"unknown11,omitempty"`                             // 0
	Msgsource     []byte                 `protobuf:"bytes,12,opt,name=msgsource" json:"msgsource,omitempty"`                              // msgsource XML
	Unknown13     []byte                 `protobuf:"bytes,13,opt,name=unknown13" json:"unknown13,omitempty"`                              // 空 (必须显式存在)
	Unknown14     []byte                 `protobuf:"bytes,14,opt,name=unknown14" json:"unknown14,omitempty"`                              // 空 (必须显式存在)
	Unknown15     []byte                 `protobuf:"bytes,15,opt,name=unknown15" json:"unknown15,omitempty"`                              // 空 (必须显式存在)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyMsgBody) Reset() {
	*x = ReplyMsgBody{}
	mi := &file_proto_wxproto_reply_msg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyMsgBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyMsgBody) ProtoMessage() {}

func (x *ReplyMsgBody) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wxproto_reply_msg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyMsgBody.ProtoReflect.Descriptor instead.
func (*ReplyMsgBody) Descriptor() ([]byte, []int) {
	return file_proto_wxproto_reply_msg_proto_rawDescGZIP(), []int{2}
}

func (x *ReplyMsgBody) GetSender() string {
	if x != nil && x.Sender != nil {
		return *x.Sender
	}
	return ""
}

func (x *ReplyMsgBody) GetUnknown2() []byte {
	if x != nil {
		return x.Unknown2
	}
	return nil
}

func (x *ReplyMsgBody) GetUnknown3() int32 {
	if x != nil && x.Unknown3 != nil {
		return *x.Unknown3
	}
	return 0
}

func (x *ReplyMsgBody) GetReceiver() string {
	if x != nil && x.Receiver != nil {
		return *x.Receiver
	}
	return ""
}

func (x *ReplyMsgBody) GetMsgType() int32 {
	if x != nil && x.MsgType != nil {
		return *x.MsgType
	}
	return 0
}

func (x *ReplyMsgBody) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ReplyMsgBody) GetSendTimestamp() int64 {
	if x != nil && x.SendTimestamp != nil {
		return *x.SendTimestamp
	}
	return 0
}

func (x *ReplyMsgBody) GetClientMsgId() string {
	if x != nil && x.ClientMsgId != nil {
		return *x.ClientMsgId
	}
	return ""
}

func (x *ReplyMsgBody) GetUnknown9() int32 {
	if x != nil && x.Unknown9 != nil {
		return *x.Unknown9
	}
	return 0
}

func (x *ReplyMsgBody) GetFlag() int32 {
	if x != nil && x.Flag != nil {
		return *x.Flag
	}
	return 0
}

func (x *ReplyMsgBody) GetUnknown11() int32 {
	if x != nil && x.Unknown11 != nil {
		return *x.Unknown11
	}
	return 0
}

func (x *ReplyMsgBody) GetMsgsource() []byte {
	if x != nil {
		return x.Msgsource
	}
	return nil
}

func (x *ReplyMsgBody) GetUnknown13() []byte {
	if x != nil {
		return x.Unknown13
	}
	return nil
}

func (x *ReplyMsgBody) GetUnknown14() []byte {
	if x != nil {
		return x.Unknown14
	}
	return nil
}

func (x *ReplyMsgBody) GetUnknown15() []byte {
	if x != nil {
		return x.Unknown15
	}
	return nil
}

var File_proto_wxproto_reply_msg_proto protoreflect.FileDescriptor

const file_proto_wxproto_reply_msg_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/wxproto/reply_msg.proto\x12\awxproto\"l\n" +
	"\x0eWxSendReplyMsg\x12/\n" +
	"\x06header\x18\x01 \x01(\v2\x17.wxproto.ReplyMsgHeaderR\x06header\x12)\n" +
	"\x04body\x18\x02 \x01(\v2\x15.wxproto.ReplyMsgBodyR\x04body\"\xb8\x01\n" +
	"\x0eReplyMsgHeader\x12\x12\n" +
	"\x04flag\x18\x01 \x01(\fR\x04flag\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\rR\ttimestamp\x12!\n" +
	"\fclient_proof\x18\x03 \x01(\fR\vclientProof\x12\x1b\n" +
	"\tdevice_id\x18\x04 \x01(\x04R\bdeviceId\x12\x1a\n" +
	"\bplatform\x18\x05 \x01(\tR\bplatform\x12\x18\n" +
	"\aversion\x18\x06 \x01(\rR\aversion\"\xc0\x03\n" +
	"\fReplyMsgBody\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x1a\n" +
	"\bunknown2\x18\x02 \x01(\fR\bunknown2\x12\x1a\n" +
	"\bunknown3\x18\x03 \x01(\x05R\bunknown3\x12\x1a\n" +
	"\breceiver\x18\x04 \x01(\tR\breceiver\x12\x19\n" +
	"\bmsg_type\x18\x05 \x01(\x05R\amsgType\x12\x18\n" +
	"\acontent\x18\x06 \x01(\fR\acontent\x12%\n" +
	"\x0esend_timestamp\x18\a \x01(\x03R\rsendTimestamp\x12\"\n" +
	"\rclient_msg_id\x18\b \x01(\tR\vclientMsgId\x12\x1a\n" +
	"\bunknown9\x18\t \x01(\x05R\bunknown9\x12\x12\n" +
	"\x04flag\x18\n" +
	" \x01(\x05R\x04flag\x12\x1c\n" +
	"\tunknown11\x18\v \x01(\x05R\tunknown11\x12\x1c\n" +
	"\tmsgsource\x18\f \x01(\fR\tmsgsource\x12\x1c\n" +
	"\tunknown13\x18\r \x01(\fR\tunknown13\x12\x1c\n" +
	"\tunknown14\x18\x0e \x01(\fR\tunknown14\x12\x1c\n" +
	"\tunknown15\x18\x0f \x01(\fR\tunknown15B>Z<github.com/yincongcyincong/weixin-macos/onebot/proto/wxproto"

var (
	file_proto_wxproto_reply_msg_proto_rawDescOnce sync.Once
	file_proto_wxproto_reply_msg_proto_rawDescData []byte
)

func file_proto_wxproto_reply_msg_proto_rawDescGZIP() []byte {
	file_proto_wxproto_reply_msg_proto_rawDescOnce.Do(func() {
		file_proto_wxproto_reply_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_wxproto_reply_msg_proto_rawDesc), len(file_proto_wxproto_reply_msg_proto_rawDesc)))
	})
	return file_proto_wxproto_reply_msg_proto_rawDescData
}

var file_proto_wxproto_reply_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_wxproto_reply_msg_proto_goTypes = []any{
	(*WxSendReplyMsg)(nil), // 0: wxproto.WxSendReplyMsg
	(*ReplyMsgHeader)(nil), // 1: wxproto.ReplyMsgHeader
	(*ReplyMsgBody)(nil),   // 2: wxproto.ReplyMsgBody
}
var file_proto_wxproto_reply_msg_proto_depIdxs = []int32{
	1, // 0: wxproto.WxSendReplyMsg.header:type_name -> wxproto.ReplyMsgHeader
	2, // 1: wxproto.WxSendReplyMsg.body:type_name -> wxproto.ReplyMsgBody
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_wxproto_reply_msg_proto_init() }
func file_proto_wxproto_reply_msg_proto_init() {
	if File_proto_wxproto_reply_msg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_wxproto_reply_msg_proto_rawDesc), len(file_proto_wxproto_reply_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_wxproto_reply_msg_proto_goTypes,
		DependencyIndexes: file_proto_wxproto_reply_msg_proto_depIdxs,
		MessageInfos:      file_proto_wxproto_reply_msg_proto_msgTypes,
	}.Build()
	File_proto_wxproto_reply_msg_proto = out.File
	file_proto_wxproto_reply_msg_proto_goTypes = nil
	file_proto_wxproto_reply_msg_proto_depIdxs = nil
}
