// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.5.1
// source: proto/wxproto/video_msg.proto

package wxproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 发送视频消息的protobuf结构
type WxSendVideoMsg struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Header      *VideoMsgHeader        `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	ClientMsgId []byte                 `protobuf:"bytes,2,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`
	Sender      []byte                 `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver    []byte                 `protobuf:"bytes,4,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Unknown5    int32                  `protobuf:"varint,5,opt,name=unknown5,proto3" json:"unknown5,omitempty"`
	Unknown6    int32                  `protobuf:"varint,6,opt,name=unknown6,proto3" json:"unknown6,omitempty"`
	Unknown7    *VideoMsgExtra         `protobuf:"bytes,7,opt,name=unknown7,proto3" json:"unknown7,omitempty"`
	Unknown8    int32                  `protobuf:"varint,8,opt,name=unknown8,proto3" json:"unknown8,omitempty"`
	Unknown9    int32                  `protobuf:"varint,9,opt,name=unknown9,proto3" json:"unknown9,omitempty"`
	Unknown10   *VideoMsgExtra         `protobuf:"bytes,10,opt,name=unknown10,proto3" json:"unknown10,omitempty"`
	Duration    int32                  `protobuf:"varint,11,opt,name=duration,proto3" json:"duration,omitempty"`
	Unknown12   int32                  `protobuf:"varint,12,opt,name=unknown12,proto3" json:"unknown12,omitempty"`
	Unknown13   int32                  `protobuf:"varint,13,opt,name=unknown13,proto3" json:"unknown13,omitempty"`
	Unknown14   int32                  `protobuf:"varint,14,opt,name=unknown14,proto3" json:"unknown14,omitempty"`
	Xml         []byte                 `protobuf:"bytes,15,opt,name=xml,proto3" json:"xml,omitempty"`
	CdnKey      []byte                 `protobuf:"bytes,16,opt,name=cdn_key,json=cdnKey,proto3" json:"cdn_key,omitempty"`
	AesKey      []byte                 `protobuf:"bytes,17,opt,name=aes_key,json=aesKey,proto3" json:"aes_key,omitempty"`
	Unknown18   int32                  `protobuf:"varint,18,opt,name=unknown18,proto3" json:"unknown18,omitempty"`
	CdnKey2     []byte                 `protobuf:"bytes,19,opt,name=cdn_key2,json=cdnKey2,proto3" json:"cdn_key2,omitempty"`
	Unknown20   int32                  `protobuf:"varint,20,opt,name=unknown20,proto3" json:"unknown20,omitempty"`
	Unknown21   int32                  `protobuf:"varint,21,opt,name=unknown21,proto3" json:"unknown21,omitempty"`
	Unknown22   int32                  `protobuf:"varint,22,opt,name=unknown22,proto3" json:"unknown22,omitempty"`
	AesKey2     []byte                 `protobuf:"bytes,23,opt,name=aes_key2,json=aesKey2,proto3" json:"aes_key2,omitempty"`
	// fields 24-25 skipped
	Md5Key []byte `protobuf:"bytes,26,opt,name=md5_key,json=md5Key,proto3" json:"md5_key,omitempty"`
	// fields 27-36 skipped
	VideoId   []byte `protobuf:"bytes,37,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Unknown38 int32  `protobuf:"varint,38,opt,name=unknown38,proto3" json:"unknown38,omitempty"`
	// fields 39-47 skipped
	Md5Key2       []byte `protobuf:"bytes,48,opt,name=md5_key2,json=md5Key2,proto3" json:"md5_key2,omitempty"`
	CdnKey3       []byte `protobuf:"bytes,49,opt,name=cdn_key3,json=cdnKey3,proto3" json:"cdn_key3,omitempty"`
	AesKey3       []byte `protobuf:"bytes,50,opt,name=aes_key3,json=aesKey3,proto3" json:"aes_key3,omitempty"`
	Unknown51     int32  `protobuf:"varint,51,opt,name=unknown51,proto3" json:"unknown51,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WxSendVideoMsg) Reset() {
	*x = WxSendVideoMsg{}
	mi := &file_proto_wxproto_video_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WxSendVideoMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WxSendVideoMsg) ProtoMessage() {}

func (x *WxSendVideoMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wxproto_video_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WxSendVideoMsg.ProtoReflect.Descriptor instead.
func (*WxSendVideoMsg) Descriptor() ([]byte, []int) {
	return file_proto_wxproto_video_msg_proto_rawDescGZIP(), []int{0}
}

func (x *WxSendVideoMsg) GetHeader() *VideoMsgHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *WxSendVideoMsg) GetClientMsgId() []byte {
	if x != nil {
		return x.ClientMsgId
	}
	return nil
}

func (x *WxSendVideoMsg) GetSender() []byte {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *WxSendVideoMsg) GetReceiver() []byte {
	if x != nil {
		return x.Receiver
	}
	return nil
}

func (x *WxSendVideoMsg) GetUnknown5() int32 {
	if x != nil {
		return x.Unknown5
	}
	return 0
}

func (x *WxSendVideoMsg) GetUnknown6() int32 {
	if x != nil {
		return x.Unknown6
	}
	return 0
}

func (x *WxSendVideoMsg) GetUnknown7() *VideoMsgExtra {
	if x != nil {
		return x.Unknown7
	}
	return nil
}

func (x *WxSendVideoMsg) GetUnknown8() int32 {
	if x != nil {
		return x.Unknown8
	}
	return 0
}

func (x *WxSendVideoMsg) GetUnknown9() int32 {
	if x != nil {
		return x.Unknown9
	}
	return 0
}

func (x *WxSendVideoMsg) GetUnknown10() *VideoMsgExtra {
	if x != nil {
		return x.Unknown10
	}
	return nil
}

func (x *WxSendVideoMsg) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *WxSendVideoMsg) GetUnknown12() int32 {
	if x != nil {
		return x.Unknown12
	}
	return 0
}

func (x *WxSendVideoMsg) GetUnknown13() int32 {
	if x != nil {
		return x.Unknown13
	}
	return 0
}

func (x *WxSendVideoMsg) GetUnknown14() int32 {
	if x != nil {
		return x.Unknown14
	}
	return 0
}

func (x *WxSendVideoMsg) GetXml() []byte {
	if x != nil {
		return x.Xml
	}
	return nil
}

func (x *WxSendVideoMsg) GetCdnKey() []byte {
	if x != nil {
		return x.CdnKey
	}
	return nil
}

func (x *WxSendVideoMsg) GetAesKey() []byte {
	if x != nil {
		return x.AesKey
	}
	return nil
}

func (x *WxSendVideoMsg) GetUnknown18() int32 {
	if x != nil {
		return x.Unknown18
	}
	return 0
}

func (x *WxSendVideoMsg) GetCdnKey2() []byte {
	if x != nil {
		return x.CdnKey2
	}
	return nil
}

func (x *WxSendVideoMsg) GetUnknown20() int32 {
	if x != nil {
		return x.Unknown20
	}
	return 0
}

func (x *WxSendVideoMsg) GetUnknown21() int32 {
	if x != nil {
		return x.Unknown21
	}
	return 0
}

func (x *WxSendVideoMsg) GetUnknown22() int32 {
	if x != nil {
		return x.Unknown22
	}
	return 0
}

func (x *WxSendVideoMsg) GetAesKey2() []byte {
	if x != nil {
		return x.AesKey2
	}
	return nil
}

func (x *WxSendVideoMsg) GetMd5Key() []byte {
	if x != nil {
		return x.Md5Key
	}
	return nil
}

func (x *WxSendVideoMsg) GetVideoId() []byte {
	if x != nil {
		return x.VideoId
	}
	return nil
}

func (x *WxSendVideoMsg) GetUnknown38() int32 {
	if x != nil {
		return x.Unknown38
	}
	return 0
}

func (x *WxSendVideoMsg) GetMd5Key2() []byte {
	if x != nil {
		return x.Md5Key2
	}
	return nil
}

func (x *WxSendVideoMsg) GetCdnKey3() []byte {
	if x != nil {
		return x.CdnKey3
	}
	return nil
}

func (x *WxSendVideoMsg) GetAesKey3() []byte {
	if x != nil {
		return x.AesKey3
	}
	return nil
}

func (x *WxSendVideoMsg) GetUnknown51() int32 {
	if x != nil {
		return x.Unknown51
	}
	return 0
}

type VideoMsgHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flag          []byte                 `protobuf:"bytes,1,opt,name=flag,proto3" json:"flag,omitempty"`
	MsgId         int64                  `protobuf:"varint,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	ClientProof   []byte                 `protobuf:"bytes,3,opt,name=client_proof,json=clientProof,proto3" json:"client_proof,omitempty"`
	Unknown4      int64                  `protobuf:"varint,4,opt,name=unknown4,proto3" json:"unknown4,omitempty"`
	SysInfo       []byte                 `protobuf:"bytes,5,opt,name=sys_info,json=sysInfo,proto3" json:"sys_info,omitempty"`
	Unknown6      int32                  `protobuf:"varint,6,opt,name=unknown6,proto3" json:"unknown6,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoMsgHeader) Reset() {
	*x = VideoMsgHeader{}
	mi := &file_proto_wxproto_video_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoMsgHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoMsgHeader) ProtoMessage() {}

func (x *VideoMsgHeader) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wxproto_video_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoMsgHeader.ProtoReflect.Descriptor instead.
func (*VideoMsgHeader) Descriptor() ([]byte, []int) {
	return file_proto_wxproto_video_msg_proto_rawDescGZIP(), []int{1}
}

func (x *VideoMsgHeader) GetFlag() []byte {
	if x != nil {
		return x.Flag
	}
	return nil
}

func (x *VideoMsgHeader) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *VideoMsgHeader) GetClientProof() []byte {
	if x != nil {
		return x.ClientProof
	}
	return nil
}

func (x *VideoMsgHeader) GetUnknown4() int64 {
	if x != nil {
		return x.Unknown4
	}
	return 0
}

func (x *VideoMsgHeader) GetSysInfo() []byte {
	if x != nil {
		return x.SysInfo
	}
	return nil
}

func (x *VideoMsgHeader) GetUnknown6() int32 {
	if x != nil {
		return x.Unknown6
	}
	return 0
}

type VideoMsgExtra struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field1        int32                  `protobuf:"varint,1,opt,name=field1,proto3" json:"field1,omitempty"`
	Field2        []byte                 `protobuf:"bytes,2,opt,name=field2,proto3" json:"field2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoMsgExtra) Reset() {
	*x = VideoMsgExtra{}
	mi := &file_proto_wxproto_video_msg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoMsgExtra) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoMsgExtra) ProtoMessage() {}

func (x *VideoMsgExtra) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wxproto_video_msg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoMsgExtra.ProtoReflect.Descriptor instead.
func (*VideoMsgExtra) Descriptor() ([]byte, []int) {
	return file_proto_wxproto_video_msg_proto_rawDescGZIP(), []int{2}
}

func (x *VideoMsgExtra) GetField1() int32 {
	if x != nil {
		return x.Field1
	}
	return 0
}

func (x *VideoMsgExtra) GetField2() []byte {
	if x != nil {
		return x.Field2
	}
	return nil
}

var File_proto_wxproto_video_msg_proto protoreflect.FileDescriptor

const file_proto_wxproto_video_msg_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/wxproto/video_msg.proto\x12\awxproto\"\x9c\a\n" +
	"\x0eWxSendVideoMsg\x12/\n" +
	"\x06header\x18\x01 \x01(\v2\x17.wxproto.VideoMsgHeaderR\x06header\x12\"\n" +
	"\rclient_msg_id\x18\x02 \x01(\fR\vclientMsgId\x12\x16\n" +
	"\x06sender\x18\x03 \x01(\fR\x06sender\x12\x1a\n" +
	"\breceiver\x18\x04 \x01(\fR\breceiver\x12\x1a\n" +
	"\bunknown5\x18\x05 \x01(\x05R\bunknown5\x12\x1a\n" +
	"\bunknown6\x18\x06 \x01(\x05R\bunknown6\x122\n" +
	"\bunknown7\x18\a \x01(\v2\x16.wxproto.VideoMsgExtraR\bunknown7\x12\x1a\n" +
	"\bunknown8\x18\b \x01(\x05R\bunknown8\x12\x1a\n" +
	"\bunknown9\x18\t \x01(\x05R\bunknown9\x124\n" +
	"\tunknown10\x18\n" +
	" \x01(\v2\x16.wxproto.VideoMsgExtraR\tunknown10\x12\x1a\n" +
	"\bduration\x18\v \x01(\x05R\bduration\x12\x1c\n" +
	"\tunknown12\x18\f \x01(\x05R\tunknown12\x12\x1c\n" +
	"\tunknown13\x18\r \x01(\x05R\tunknown13\x12\x1c\n" +
	"\tunknown14\x18\x0e \x01(\x05R\tunknown14\x12\x10\n" +
	"\x03xml\x18\x0f \x01(\fR\x03xml\x12\x17\n" +
	"\acdn_key\x18\x10 \x01(\fR\x06cdnKey\x12\x17\n" +
	"\aaes_key\x18\x11 \x01(\fR\x06aesKey\x12\x1c\n" +
	"\tunknown18\x18\x12 \x01(\x05R\tunknown18\x12\x19\n" +
	"\bcdn_key2\x18\x13 \x01(\fR\acdnKey2\x12\x1c\n" +
	"\tunknown20\x18\x14 \x01(\x05R\tunknown20\x12\x1c\n" +
	"\tunknown21\x18\x15 \x01(\x05R\tunknown21\x12\x1c\n" +
	"\tunknown22\x18\x16 \x01(\x05R\tunknown22\x12\x19\n" +
	"\baes_key2\x18\x17 \x01(\fR\aaesKey2\x12\x17\n" +
	"\amd5_key\x18\x1a \x01(\fR\x06md5Key\x12\x19\n" +
	"\bvideo_id\x18% \x01(\fR\avideoId\x12\x1c\n" +
	"\tunknown38\x18& \x01(\x05R\tunknown38\x12\x19\n" +
	"\bmd5_key2\x180 \x01(\fR\amd5Key2\x12\x19\n" +
	"\bcdn_key3\x181 \x01(\fR\acdnKey3\x12\x19\n" +
	"\baes_key3\x182 \x01(\fR\aaesKey3\x12\x1c\n" +
	"\tunknown51\x183 \x01(\x05R\tunknown51\"\xb1\x01\n" +
	"\x0eVideoMsgHeader\x12\x12\n" +
	"\x04flag\x18\x01 \x01(\fR\x04flag\x12\x15\n" +
	"\x06msg_id\x18\x02 \x01(\x03R\x05msgId\x12!\n" +
	"\fclient_proof\x18\x03 \x01(\fR\vclientProof\x12\x1a\n" +
	"\bunknown4\x18\x04 \x01(\x03R\bunknown4\x12\x19\n" +
	"\bsys_info\x18\x05 \x01(\fR\asysInfo\x12\x1a\n" +
	"\bunknown6\x18\x06 \x01(\x05R\bunknown6\"?\n" +
	"\rVideoMsgExtra\x12\x16\n" +
	"\x06field1\x18\x01 \x01(\x05R\x06field1\x12\x16\n" +
	"\x06field2\x18\x02 \x01(\fR\x06field2B>Z<github.com/yincongcyincong/weixin-macos/onebot/proto/wxprotob\x06proto3"

var (
	file_proto_wxproto_video_msg_proto_rawDescOnce sync.Once
	file_proto_wxproto_video_msg_proto_rawDescData []byte
)

func file_proto_wxproto_video_msg_proto_rawDescGZIP() []byte {
	file_proto_wxproto_video_msg_proto_rawDescOnce.Do(func() {
		file_proto_wxproto_video_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_wxproto_video_msg_proto_rawDesc), len(file_proto_wxproto_video_msg_proto_rawDesc)))
	})
	return file_proto_wxproto_video_msg_proto_rawDescData
}

var file_proto_wxproto_video_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_wxproto_video_msg_proto_goTypes = []any{
	(*WxSendVideoMsg)(nil), // 0: wxproto.WxSendVideoMsg
	(*VideoMsgHeader)(nil), // 1: wxproto.VideoMsgHeader
	(*VideoMsgExtra)(nil),  // 2: wxproto.VideoMsgExtra
}
var file_proto_wxproto_video_msg_proto_depIdxs = []int32{
	1, // 0: wxproto.WxSendVideoMsg.header:type_name -> wxproto.VideoMsgHeader
	2, // 1: wxproto.WxSendVideoMsg.unknown7:type_name -> wxproto.VideoMsgExtra
	2, // 2: wxproto.WxSendVideoMsg.unknown10:type_name -> wxproto.VideoMsgExtra
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_wxproto_video_msg_proto_init() }
func file_proto_wxproto_video_msg_proto_init() {
	if File_proto_wxproto_video_msg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_wxproto_video_msg_proto_rawDesc), len(file_proto_wxproto_video_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_wxproto_video_msg_proto_goTypes,
		DependencyIndexes: file_proto_wxproto_video_msg_proto_depIdxs,
		MessageInfos:      file_proto_wxproto_video_msg_proto_msgTypes,
	}.Build()
	File_proto_wxproto_video_msg_proto = out.File
	file_proto_wxproto_video_msg_proto_goTypes = nil
	file_proto_wxproto_video_msg_proto_depIdxs = nil
}
